server:
  port: 8080

app:
  jwtSecret: rosalindSecretKey
  jwtExpirationMs: 86400000

logging:
  level:
    org.springframework: INFO
    com.rosalind: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
